spring.application.name=banking-faq-assistant

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:bankingfaq}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Vector Store Initialization
spring.ai.vectorstore.pgvector.initialize-schema=true

# Global switch to activate the Google GenAI Embedding Bean
spring.ai.model.embedding.text=google-genai

# Chat connection
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Embedding connection ? needs its own api-key, despite the docs implying it's shared
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

# Chat Configuration
spring.ai.google.genai.chat.model=gemini-2.5-flash

# Embedding Configuration
spring.ai.google.genai.embedding.text.model=gemini-embedding-2
spring.ai.google.genai.embedding.text.dimensions=768

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

spring.config.import=optional:file:.env[.properties]